apiVersion: v1
kind: Service
metadata:
  name: {{ include "langflow.fullname" . }}
  labels:
    app: {{ template "langflow.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "langflow.name" . }}
    component: "{{ .Values.name }}"
    release: {{ .Release.Name }}
